### ISSUE TITLE
Kuchiki for generating HTML reports

### ISSUE THREAD

**Issue by SimonSapin** [kuchiki-rs/kuchiki#11]
@brson asked on IRC:

> I have a tool that wants to output html reports. Is kuchiki right for that? Is it ready?

You can in theory build up a tree with `NodeRef::new_element`, `NodeRef::new_text`, and `NodeRef::append` and then call the HTML serializer on it, but it’s not gonna be convenient.

Right now, the best I can recommend is `write!`’ing repeatedly to a `String`. Eventually, I expect the Rust ecosystem to grow templating libraries like http://jinja.pocoo.org/docs/dev/ . Jinja just emits text, and sometimes that text happens to be in HTML syntax. Genshi http://genshi.edgewall.org/ is a bit different in that it is based on XML/HTML trees rather than text, so the end result is guaranteed to be [well-formed](http://www.w3.org/TR/REC-xml/#sec-well-formed), but that’s not really a big deal now that HTML has standardized permissive error recovery in the parser. A Genshi-like templating library in Rust could be based on Kuchiki, but would be more than just what Kuchiki does.

Regarding Kuchiki being ready: it lack tutorial-style documentation, but other than that it should work. In theory, as I’m not aware of “real” projects using it yet. Feedback welcome!

**Comment by gwicke** [comment]
> that’s not really a big deal now that HTML has standardized permissive error recovery in the parser

Building up HTML from strings often leads to XSS security issues. It is however possible to compile a DOM-based template to a string-based expansion system, and get both context-sensitive escaping / well-formedness _and_ decent performance. An example in JS would be my own https://github.com/gwicke/knockoff and https://github.com/gwicke/tassembly.

**Comment by SimonSapin** [comment]
Yes, there are certainly interesting things to do in that space, perhaps even at compile-time with the Rust type system!

**Comment by Ygg01** [comment]
Looking at XSS resistant templates what about [Shakespearan](http://www.yesodweb.com/book/shakespearean-templates) templates from Haskell?

**Comment by SimonSapin** [comment]
I will soon archive this repository and make it read-only, so this issue will not be addressed: https://github.com/kuchiki-rs/kuchiki#archived
