### ISSUE TITLE
Can't use kuchiki as dependency. 

### ISSUE THREAD

**Issue by Ygg01** [kuchiki-rs/kuchiki#13]
I tried using kuchiki as dependency on rust `stable` and `nightly`, and it didn't work. 

Here are steps to reproduce:
1. Run `cargo new test` and navigate to project
2. In `Cargo.toml` add following lines:
     [dependencies]
     kuchiki = "0.0.1"
3. Run `cargo build` on the created project.

Expected: build project
Got: `Unable to get packages from source.`

Perhaps a new version should be deployed to crates.io? I've added other projects just fine (e.g. hyper).

**Comment by SimonSapin** [comment]
That’s because Kuchiki has never been properly published on crates.io. https://crates.io/crates/kuchiki only has the bare minimum to reserve the name.

For now I recommend using a git dependency:

``` toml
[dependencies]
kuchiki = { git = "https://github.com/SimonSapin/kuchiki" }
```

**Comment by Ygg01** [comment]
Many thanks.

Then you may close this issue, unless it's important to track kuchiki crate availability.

**Comment by SimonSapin** [comment]
To clarify, Kuchiki and rust-selectors are not on crate.io _yet_ but only because nobody asked. Let me know if you’d prefer that rather than use a git dependency.

**Comment by SimonSapin** [comment]
I’ve published https://crates.io/crates/kuchiki v0.1.0
