### ISSUE TITLE
selectors::Element not properly exported

### ISSUE THREAD

**Issue by sheganinans** [kuchiki-rs/kuchiki#23]
I'm trying to use the methods from: https://simonsapin.github.io/kuchiki/selectors/trait.Element.html

In particular: `get_local_name()`, `get_namespace()`.

However I get the error:

``` text
src/main.rs:64:14: 64:27 error: no method named `get_namespace` found for type `kuchiki::node_data_ref::NodeDataRef<kuchiki::tree::ElementData>` in the current scope
src/main.rs:64  m.get_namespace();
                  ^~~~~~~~~~~~~
src/main.rs:64:14: 64:27 help: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
src/main.rs:64:14: 64:27 help: candidate #1: `use selectors::tree::Element`
error: aborting due to previous error
```

But I cannot `use selectors::tree::Element;` because it is private.

If I `extern crate selectors; use selectors::Element;` I get exactly the same error.

**Comment by sheganinans** [comment]
I updated to the latest 0.5.2 and it fixed the problem. Excellent library, thanks!

**Comment by SimonSapin** [comment]
I consider this trait not to be part of Kuchiki’s public API. It’s more like a bunch of callbacks given to the `selectors` library. If you have `m: NodeDataRef<ElementData>` you can simply access its fields: `m.name.local`, `m.name.ns`. https://simonsapin.github.io/kuchiki/kuchiki/struct.ElementData.html

**Comment by sheganinans** [comment]
Beautiful, thanks for the tip! I'm kinda new to Rust, I appreciate the help!
