### ISSUE TITLE
Error parsing Tag when no close Tag

### ISSUE THREAD

**Issue by LeMoussel** [kuchiki-rs/kuchiki#25]
Hello,

I want to get all links on this page:  [http://cocon.se/](http://cocon.se/)
Here's my code I'm using to try to get links (for test, html page is save in local file: cocon1.html):

```
    let html_file =  Path::new("cocon1.html").to_path_buf();
    let document = kuchiki::parse_html().from_utf8().from_file(&html_file).unwrap();
    for link in document.select("a").unwrap() {
        let attributes = link.attributes.borrow();
        println!("{:?} {}", attributes.get("href"), link.text_contents());
    }
```

I got this result :

> Some("http://cocon.se/")
> Some("http://cocon.se/visualisation/") Visualisations
> Some("http://cocon.se/cocon-semantique/") Cocon Sémantique
> Some("http://cocon.se/a-propos/") A propos
> Some("http://cocon.se/#focus") Quoi c'est ?
> Some("http://cocon.se/#focus") J'en suis !
> Some("http://twitter.com/Lemoussel")
> Some("http://twitter.com/SylvainDeaure")
> None Johann
> None Sylvain V.
> None Fabrice
> Some("/cas/") Etude de cas
> Some("/actus/") Actus
> Some("/historique/") Historique
> Some("http://cocon.se/cas/astuce1.html")
> Some("http://cocon.se/cas/astuce1.html") Une astuce de grand mère
> Some("http://cocon.se/cas/jouer.html")
> Some("http://cocon.se/cas/jouer.html") A vous de jouer !
> Some("http://cocon.se/actus/gagner-tableau.html")
> Some("http://cocon.se/actus/gagner-tableau.html") Qui veut gagner des tableaux ?
> Some("http://cocon.se/actus/gagner-tableau.html") […]
> Some("http://cocon.se/historique/cocon-con.html")
> Some("http://cocon.se/historique/cocon-con.html") Un cocon moins con
> Some("#carousel-homepage-latestnews") Previous
> Some("#carousel-homepage-latestnews") Next
> Some("mailto:blog@cocon.se") blog@cocon.se
> Some("http://twitter.com/SylvainDeaure")
> Some("/mentions/") Mentions légales
> Some("/mentions/")
> 
> Some("/mentions/")
> 
> Some("/mentions/")
> 
> /\* <![CDATA[ _/
> var post_notif_widget_ajax_obj = {"ajax_url":"http:\/\/cocon.se\/wp-admin\/admin-ajax.php","nonce":"fbaa1fb825","processing_msg":"Processing..."};
> /_ ]]> */

Last 3 lines `Some("/mentions/")` are incorrect. There is only one link `/mentions/` with text `Mentions légales` in HTML page.

This error seems to be due as the last `<a>` tag is not closed => `</a</div>`
`class="zerif-copyright" href="/mentions/">Mentions légales</a</div>`

Is it possible to parse HTML page with errors?

**Comment by SimonSapin** [comment]
I will soon archive this repository and make it read-only, so this issue will not be addressed: https://github.com/kuchiki-rs/kuchiki#archived
