### ISSUE TITLE
Processing Instruction tokens in Kuchiki

### ISSUE THREAD

**Issue by Ygg01** [kuchiki-rs/kuchiki#34]
From what I understand, @quininer had some troubles adding XML support (see #31 , https://github.com/quininer/sanngaa) to kuchiki. Namely, there are no Processing Instructions token/node in kuchiki, which makes sense, seeing it was made to parse HTML, which doesn't have that token.

Is this something that kuchiki could work around, or should we wait for markup5ever?

**Comment by SimonSapin** [comment]
Do you mean processing instructions nodes? I don’t mind taking a PR adding those before the markup5ever refactor.

**Comment by Ygg01** [comment]
I'll try to make a PR soonish. 

BTW, how is the markup5ever refactor going and can I help around that?

**Comment by SimonSapin** [comment]
Unfortunately it’s not really going, in the sense that @nox and I are both busy with other things.

**Comment by SimonSapin** [comment]
@Ygg01 I’ve filed https://github.com/servo/html5ever/issues/266 with a rough plan, in case you want to send PRs :) (Though we might want a branch for this.)

**Comment by SimonSapin** [comment]
I will soon archive this repository and make it read-only, so this issue will not be addressed: https://github.com/kuchiki-rs/kuchiki#archived
