### ISSUE TITLE
Pseudo class selector support

### ISSUE THREAD

**Issue by laplaceon** [kuchiki-rs/kuchiki#43]
Is it possible to add support for selectors like "div.class p:has(span.something:contains(SomeText)) a" which have pseudo class selectors like ":has" and ":contains"?

**Comment by SimonSapin** [comment]
It is possible. I have no plan to work on this, however.

(`:has` is specified at https://drafts.csswg.org/selectors/#relational, but `:contains` appears to be non-standard.)

**Comment by SimonSapin** [comment]
I will soon archive this repository and make it read-only, so this issue will not be addressed: https://github.com/kuchiki-rs/kuchiki#archived
