### ISSUE TITLE
Table-related tags seem to get ignored completely

### ISSUE THREAD

**Issue by lamafab** [kuchiki-rs/kuchiki#46]
Hi

Tags such as `<tbody>`, `<tr>` and `<td>` seem to get ignored completely by the parser.

```
let html = "
    <tbody>
        <td colspan=\"2\">Example 1</td>
    </tbody>
    <p>Example 2</p>
";

let document = kuchiki::parse_html().one(html);

for node in document.descendants() {
    if let Some(element) = node.as_element() {
        println!("{:?}", element.name.local);
    }
}
```

Output

```
Atom('html' type=static)
Atom('head' type=static)
Atom('body' type=static)
Atom('p' type=static)
```

Does `html5ever` currently omit those tags or are they handled in a different way? Calling ```.data()``` on `NodeRef` will not show any presence of those tags neither.

Any advice is greatly appreciated.

**Comment by tabatkins** [comment]
That's correct parser behavior - kuchiki isn't parsing a fragment, it's parsing a document, and random improperly nested internal table elements have some... unusual parsing behavior.

You can see the same effect in browsers at <http://software.hixie.ch/utilities/js/live-dom-viewer/saved/6179> - check the DOM pane, and note how the table elements are gone.

Simon will have to answer whether there's a way to invoke kuchiki as a fragment parser, I'm not familiar enough with it to know.

**Comment by SimonSapin** [comment]
html5ever does support fragment parsing, so adding it to Kuchiki should be easy enough if someone wants to make a PR.

**Comment by lamafab** [comment]
Thank you for the answers!

@SimonSapin That's great to hear; for my current project I'm pretty much forced to use fragments. I'll try to do it with ```html5ever```, but I'm planing on implementing it in ```kuchiki``` directly. A PR will follow soon (no promises on when exactly...)
