### ISSUE TITLE
How to create an empty element?

### ISSUE THREAD

**Issue by sanmai-NL** [kuchiki-rs/kuchiki#52]
E.g. a `link` element is an [empty element](https://developer.mozilla.org/en-US/docs/Glossary/empty_element). Looking through the API docs, examples and tests I couldn't figure out how to create such an element using `kuchiki`.

**Comment by SimonSapin** [comment]
As far as I know this is a concern for the parser and serializer for a given syntax (e.g. HTML or XML). In a DOM-like tree data structure, such elements are not special, they are represented simply as element nodes that happen not to have any children.

To create one from Rust code, call for example [`NodeRef::new_element`](https://docs.rs/kuchiki/0.7.2/kuchiki/struct.NodeRef.html#method.new_element) and then don’t call methods like `append`. To create one by parsing HTML syntax, `html5ever` will already take care of parsing `<link>` correctly.

**Comment by sanmai-NL** [comment]
The parser used in e.g. Firefox and HTML validators will flag empty elements serialized as normal elements but empty as syntax errors in the strict sense. Using `new_element` without `append` is what I happened to do, but I did call `append` on the containing element in order to place the empty element as child, resulting in `<link ...></link>`.

**Comment by SimonSapin** [comment]
This sounds like a bug in html5ever’s serializier, or in kuchiki’s use of it.

**Comment by vainiovano** [comment]
I read some of html5ever's documentation and got a solution: use namespace `html` like this: `QualName::new(None, ns!(html), local_name!("link"))`. This will make it work correctly.

**Comment by SimonSapin** [comment]
I will soon archive this repository and make it read-only, so this issue will not be addressed: https://github.com/kuchiki-rs/kuchiki#archived
