### ISSUE TITLE
Update cssparser

### ISSUE THREAD

**Issue by RazrFalcon** [kuchiki-rs/kuchiki#53]

**Comment by SimonSapin** [comment]
Isn’t cssparser a private dependency in Kuchiki? Either way, I’d take a PR.

**Comment by RazrFalcon** [comment]
There are some breaking changes and I'm not sure how to resolve them.

**Comment by kpcyrd** [comment]
html5ever is also outdated now. I'm about to upload kuchiki to debian as soon as all dependency are accepted, even if this is a private dependency we would either need upload an old version of cssparser (and the dependency of that specific version which are outdated as well), or write a patch that uses the latest versions, which unfortunately seems non-trivial according to @RazrFalcon's comment.

An update would be very appreciated!

**Comment by SimonSapin** [comment]
https://crates.io/crates/kuchiki/0.7.3 depends on cssparser 0.25 and html5ever 0.23. (And does not contain code changes, so I’m not sure what those breaking changes were.)

**Comment by kpcyrd** [comment]
Awesome, thank you!
