### ISSUE TITLE
Support for :contains("foo")

### ISSUE THREAD

**Issue by kpcyrd** [kuchiki-rs/kuchiki#58]
I'm not sure if this needs to be implemented in one of the servo crates or kuchiki, but I noticed it's currently not supported and it would be very useful to have.

Thanks!

**Comment by SimonSapin** [comment]
`:contains` is not part of CSS: https://drafts.csswg.org/selectors/. I’m not even sure what it’s supposed to do.

**Comment by kpcyrd** [comment]
hah, oops. It seems the website I've tested this on had jquery loaded, so I didn't get the browser native `$(selector)` that uses css selectors, but the jquery `$(selector)` that uses it's own thing.

Sorry for the noise.
