### ISSUE TITLE
README.md update with working recipes

### ISSUE THREAD

**Issue by toinbis** [kuchiki-rs/kuchiki#59]
Hi Simon,

following your "Sorry for the lack of tutorial-like documentation for html5ever and tendril…" statement in https://stackoverflow.com/questions/35654525/parsing-html-page-content-in-a-stream-with-hyper-and-html5ever/35660699#35660699 i'd like to ask whether you'd accept a pull request to modify kuchiki's repo README.md with a few basic copy-paste ready examples on how to:
- parse html document from string;
- select first element matched by selector;
- add all elements matched by selector to a Vector;
- remove element(s) from the tree;
- serialize document to string;

That's all I've managed to achieve so far :)

I am writting my first rust code ever, without having any knowledge on dom manipulation algorithms, with library that has close to zero documentation. That is pain and took too many hours already to get even the most basic examples working... which could have been just copy-pasted from docs. Some examples are put in `src/tests.rs` but all the begginers will probably be diverted to https://docs.rs/kuchiki/ which they will dive into only of they are very brave and most likely not getting anywhere from there anyways.

Currently I do the examples research by following a comment on your post in stackoverflow mentioned above - "For example code you can run a search for `extern crate kuchiki` on github".  That is not an elegant process :) 

I sense you'd be keen on preparing the 'proper' tutorial and that definitely takes a lot of time, my suggestion is let's just drop 10-20 copy-paste'able examples in the readme, it'd be 20% achieving 80%, at least for newbies like me. Am ready to get started with providing a pull request with my not necessary elegant, but working examples.

**Comment by jdm** [comment]
I would be inclined to have those as example programs and link to them from the readme, rather than adding lots of examplesto the readme.

**Comment by Ygg01** [comment]
@jdm I remember there being cargo-script for examples, but I'm unsure what Rust uses for example running these days?

**Comment by jdm** [comment]
cargo run --example foo

**Comment by SimonSapin** [comment]
I will soon archive this repository and make it read-only, so this issue will not be addressed: https://github.com/kuchiki-rs/kuchiki#archived
