### ISSUE TITLE
How can I wrap an Element with a new Element?

### ISSUE THREAD

**Issue by andrewbanchich** [kuchiki-rs/kuchiki#62]
Thanks @SimonSapin for this awesome library! I am having a bit of trouble manipulating the DOM though and can't find any examples of how to do this.

I am using `traverse()` to iterate over `NodeEdge`s, then parse their attributes. I want to wrap certain elements I find in a new Element I define during the iteration.

For example, I want to find `<a href="whatever">my link</a>` and transform it to this: `<h1><a href="whatever">my link</a></h1>`.

How can I go about doing so?

Thank you

**Comment by SimonSapin** [comment]
You’ll need to remove the element with `detatch`, create the wrapper, and insert it back with either `insert_before` on the `next_sibling` if there’s one or with `append` on the `parent` if not.

**Comment by andrewbanchich** [comment]
Awesome, that worked! Thanks!
