### ISSUE TITLE
Helping maintain kuchiki

### ISSUE THREAD

**Issue by Ygg01** [kuchiki-rs/kuchiki#66]
I see a lot of PR rotting on the vine, maybe I or someone else can get access to Kuchiki and help to fix some of these issues? I volunteer if no one else wants to do it.

**Comment by SimonSapin** [comment]
Thank you for volunteering, this is very welcome. You should have an invite for this github org which gives access to this repository and to publish on crates.io.

**Comment by Ygg01** [comment]
@SimonSapin Hm. The invitation hasn't arrived. Or I am too dumb to see. It's probably the latter.

**Comment by SimonSapin** [comment]
Hmm, do you see something under https://github.com/kuchiki-rs ? Or in your notifications?

**Comment by Ygg01** [comment]
Hmm, until what seems little a while ago. I didn't. Must be some browser caching issue.

**Comment by Ygg01** [comment]
Thanks a bunch Simon!
