### ISSUE TITLE
Configureable memory limit

### ISSUE THREAD

**Issue by Kixiron** [kuchiki-rs/kuchiki#72]
I’ve been running into an issue where large documents being parsed cause massive amounts of memory usage that can slow or even crash my server and the ability to limit the memory usage of kuchiki would be invaluable. Having a memory limit could also allow the usage of preallocated buffers, which would do wonders for performance as well

**Comment by jdm** [comment]
This library is passively maintained at best, and this feature is unlikely to be implemented unless it's contributed by somebody who wants it.

**Comment by SimonSapin** [comment]
I will soon archive this repository and make it read-only, so this issue will not be addressed: https://github.com/kuchiki-rs/kuchiki#archived
