### ISSUE TITLE
NodeData is unnecessarily large, bloating the size of all Nodes

### ISSUE THREAD

**Issue by jdm** [kuchiki-rs/kuchiki#73]
`mem::size_of::<Node>()` reports 120 bytes, and `mem::size_of::<NodeData>()` makes up 80 of those bytes. If we box most of the variants of the NodeData enum, this can shrink to 56 and 16 bytes respectively.

**Comment by jdm** [comment]
Unfortunately in testcase from https://github.com/servo/html5ever/issues/420#issuecomment-644236225, this only reduces the memory usage by ~450mb. Not nothing, but need to keep investigating where all the memory is going.

**Comment by SimonSapin** [comment]
Some discussion in https://github.com/kuchiki-rs/kuchiki/pull/74#issuecomment-653157508

**Comment by SimonSapin** [comment]
I will soon archive this repository and make it read-only, so this issue will not be addressed: https://github.com/kuchiki-rs/kuchiki#archived
