### ISSUE TITLE
Implement AsRef<NodeRef> for NodeDataRef?

### ISSUE THREAD

**Issue by robinkrahl** [kuchiki-rs/kuchiki#76]
`NodeDataRef` provides a reference to its `NodeRef` with the `as_node()` method.  Could it also implement `AsRef<NodeRef>`? That would make it easier to write methods that can accept either a `NodeDataRef` or a `NodeRef`.

**Comment by SimonSapin** [comment]
I will soon archive this repository and make it read-only, so this issue will not be addressed: https://github.com/kuchiki-rs/kuchiki#archived
