### ISSUE TITLE
Support for parsing fragments

### ISSUE THREAD

**Issue by hipstermojo** [kuchiki-rs/kuchiki#77]
Hello, I wanted to know if there are plans to add support for parsing fragments. I am extracting the content within in a `noscript` tag which is represented as a string and since it can contain a number of HTML nodes after parsing, the only way this can be done is if there was a way to parse fragments.

**Comment by jdm** [comment]
This crate is passively maintained, but I think we should be able to merge https://github.com/kuchiki-rs/kuchiki/pull/47.

**Comment by hipstermojo** [comment]
Is there a soft deadline for when the merge will be made? Alternatively, is it possible to work with what is in the PR for now?

**Comment by Ygg01** [comment]
@hipstermojo Not sure, what you mean by merge? I merged #47 and published a new Kuchiki version? Does this require additional work?

**Comment by hipstermojo** [comment]
Oh sorry. I hadn't checked crates.io since Tuesday. I assumed it would have meant this issue would have been closed too. My bad.

**Comment by Ygg01** [comment]
My apology. I am relatively inexperienced at maintaining open source repos. Live and learn.
