### ISSUE TITLE
Question: Equivalent of innerHTML method

### ISSUE THREAD

**Issue by hipstermojo** [kuchiki-rs/kuchiki#80]
The `innerHTML` method in the DOM API returns a string of the HTML structure of an element node. Is there an efficient way to make such a function call in Kuchiki? The thing that comes closest for me, is:
```rust
node_ref.serialize()
```
which can then be converted to a `String` but this looks very inefficient if it is repeatedly called.

**Comment by SimonSapin** [comment]
`.innerHTML` in the DOM likely has similar (in)efficiency as `.serialize()` in Kuchiki. Unless some browsers silently cache it, but I don’t know if accessing it repeatedly without changing that subtree is common enough that such a cache would be worth the memory usage.

**Comment by hipstermojo** [comment]
Alright. Thanks for the response.
