### ISSUE TITLE
Node.to_string()

### ISSUE THREAD

**Issue by jonathan-s** [kuchiki-rs/kuchiki#84]
It would be nice if there was a function for a node that made the node and all it's children into the equivalent html.

**Comment by SimonSapin** [comment]
Looks like https://docs.rs/kuchiki/0.8.1/kuchiki/struct.NodeRef.html#method.to_string already exists.

**Comment by SimonSapin** [comment]
I will soon archive this repository and make it read-only, so this issue will not be addressed: https://github.com/kuchiki-rs/kuchiki#archived
